### ISSUE TITLE
[질문] 타입 정의 질문드립니다.

### ISSUE THREAD

**Issue by uhgenie7** [starkoora/wanted-pre-onboarding-challenge-fe-1#14]
- useQuery와 엮이면서 type이 꼬인 것 같은데 바로 잡기 어려워 조언을 구합니다...
[에러난 부분](https://han.gl/rmxJG)

- 나름대로 방법을 요리조리 찾아보았으나 다른 타입에러가 발생합니다.
[에러난 부분2](https://han.gl/CkQOZ)

- 문제가 발생하는 코드는 아래와 같습니다.
[깃허브](https://github.com/uhj1993/wanted-pre-onboarding-challenge-fe-1/commit/cd2c6ceb520e22139a7e63f33c8452fcbb191415)

참고로 [[...freshTodos]](https://github.com/uhj1993/wanted-pre-onboarding-challenge-fe-1/blob/3%ED%9A%8C%EC%B0%A8/client/src/components/molecules/TodoList.tsx#L22)를 쓴 이유는 reverse() 메서드를 써주었을 때 원본 배열을 유지하기 위해 썼습니다.

(여담인데 라벨 지정이 안 되네요)

**Comment by starkoora** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/109899564/185026854-873ad41a-e7d6-47f0-845e-932c1031c3b9.png">

@uhj1993 useQuery에 지정해주신 제네릭을 제거하고 `getTodoListAPI`의 리턴 값을 그대로 사용하도록 하시면 됩니다

```ts
export const useGetTodoListQuery = ({ errorHandler }: IErrorHandler) => {
  return useQuery(['todoList'], () => getTodoListAPI(errorHandler));
};
```

**Comment by uhgenie7** [comment]
아니 세상에...! 감사합니다!
