### ISSUE TITLE
오랜만에 질문 드립니다.  

### ISSUE THREAD

**Issue by uhgenie7** [starkoora/wanted-pre-onboarding-challenge-fe-1#17]
요즘 컴포넌트 디자인 패턴에 대한 고민으로 머리를 싸매고 있는데요,
어려울 땐 material-ui를 참조하라고 하셨는데 core한 부분은 라이브러리를 직접 깔아서 node_module 로 확인해보는 수밖에 없나요? 

예를 들어 Button 컴포넌트는 `import Button from '@mui/material/Button';` 이렇게 import 해서 사용하는데, Button 내부가 어떻게 짜여진 컴포넌트인지 웹상으로는 찾아도 잘 안 보이더라고요. 

쉽게 확인할 수 있는 경로가 있다면 댓글 부탁드리겠습니다 ㅠㅠ

**Comment by starkoora** [comment]
@uhgenie7 웹상에서 찾을 수 없다뇨 그럴리가요 ㅎㅎ

1. https://github.com/mui 에서 material-ui 선택
<img width="818" alt="image" src="https://user-images.githubusercontent.com/109899564/192582550-cc57a000-4f62-4743-ac8b-ddc5f400a434.png">

2. `packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.tsx` 경로로 진입
<img width="781" alt="image" src="https://user-images.githubusercontent.com/109899564/192582603-b1e382b4-04d1-4582-bb28-b25e4f8abc15.png">

몇 가지 라이브러리들 레포지토리 돌아다니다보면 어디에 뭐가 들어있는지 찾는 요령도 생기실겁니다 :)

**Comment by uhgenie7** [comment]
늦은 시간에 스샷까지 친절히 남겨주셔서 감사합니다! 혹시 참조해보실 다른 분들을 위해 아래 직링크 남기고 이슈 닫겠습니다 :) 

[React components that implement Google's Material Design.](https://github.com/mui/material-ui/tree/master/packages/mui-material)
