### ISSUE TITLE
과제 설명 중 최소한의 push 기능을 가진 useRouter Hook이 뭔지 모르겠습니다.

### ISSUE THREAD

**Issue by ysjkof** [starkoora/wanted-pre-onboarding-challenge-fe-1#20]
4) 최소한의 push 기능을 가진 useRouter Hook을 작성한다.
```ts
const { push } = useRouter();
```

위처럼 과제 안내가 돼 있는데 요구하는게 뭔지 모르겠습니다.

`push(url:string)`하면 URL 바꾸는 기능을 구현하는 건가요?

**Comment by starkoora** [comment]
넵 말씀해주신대로 별도 옵션 제외하고 첫 번째 인자로 url을 받아 브라우저의 주소를 바꾸는 기능을 최소한 구현해달라는 의미였습니다. 추가로 옵션 객체를 받도록 하셔도 좋습니다.

**Comment by ysjkof** [comment]
고맙습니다.
