### ISSUE TITLE
[질문] React에서 Headless를 구현할 수 있는 방법

### ISSUE THREAD

**Issue by young-st511** [starkoora/wanted-pre-onboarding-challenge-fe-1#26]
어제(01/10) 강의에서 강사님께서 React에서 Headless를 구현할 수 있는 방법 중 context가 있다고 말씀하셨는데 해당 부분이 이해가 잘 되지 않습니다ㅜㅜ 혹시 설명해주실 분 계실까요...?

+ 추가질문: 이슈 페이지에서 Label이 삭제되었나요..?

**Comment by ybw903** [comment]
어제 강의 중에 제가 기억하기로는 `Headless`가 아니라 `Dependency Injection(의존성 주입)`를 구현하는 방법으로 [context api](https://ko.reactjs.org/docs/context.html)가 될 수 있지 않을까 하고 이야기하신걸로 기억해요!
그리고 `Headless`는 `관심사의 분리`를 설명해 주시기 위해  이야기 해주신걸로 기억하고 있어요!
`기능`과 `스타일`을 제공하는 UI프레임워크 들중, [Headless UI](https://headlessui.com/react/menu)와 [@mui/base](https://mui.com/base/getting-started/overview/) 는 `스타일`을 관심사에서 제외 시키고 `기능`만 관심을 가지고 제공해 준다 이런식으로 설명해주셨던것 같아요!

**Comment by not-using** [comment]
앗 질문 포인트가 조금 달랐네요 headless 설명해주시면서 context와 유사하다고 말씀하셨던 걸로 기억하고 있어서 적었던 내용이었는데 구현 방법을 여쭤보셨군요.. 수정합니다 😂

**Comment by young-st511** [comment]
> 어제 강의 중에 제가 기억하기로는 `Headless`가 아니라 `Dependency Injection(의존성 주입)`를 구현하는 방법으로 [context api](https://ko.reactjs.org/docs/context.html)가 될 수 있지 않을까 하고 이야기하신걸로 기억해요!
> 그리고 `Headless`는 `관심사의 분리`를 설명해 주시기 위해 이야기 해주신걸로 기억하고 있어요!
> `기능`과 `스타일`을 제공하는 UI프레임워크 들중, [Headless UI](https://headlessui.com/react/menu)와 [@mui/base](https://mui.com/base/getting-started/overview/) 는 `스타일`을 관심사에서 제외 시키고 `기능`만 관심을 가지고 제공해 준다 이런식으로 설명해주셨던것 같아요!

앗 제가 헷갈렸었군요! 의존성 주입 좀 더 찾아봐야겠습니다..ㅋㅋㅋ 감사합니다!

**Comment by young-st511** [comment]
> 앗 질문 포인트가 조금 달랐네요 headless 설명해주시면서 context와 유사하다고 말씀하셨던 걸로 기억하고 있어서 적었던 내용이었는데 구현 방법을 여쭤보셨군요.. 수정합니다 😂

오잉 이전에 주신 내용 많이 도움 되었습니다! 컨텍스트를 상태관리만 생각하고 있었는데 메서드도 내려줄 수 있는 건 생각을 못했네요ㅎㅎㅎ 감사합니다!

**Comment by starkoora** [comment]
@notusing11 이 답변 내용 좋았는데 왜 삭제하셨나요 ㅠ 아까워서 살려둡니다 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/109899564/211967500-f4e2812a-9345-4564-882a-d5ac9eafd2f7.png">
