### ISSUE TITLE
[제안] api 서버의 authorization 미들웨어에서 token 없는 경우 응답 상태코드

### ISSUE THREAD

**Issue by dhsimpson** [starkoora/wanted-pre-onboarding-challenge-fe-1#30]
인증 토큰이 없는 경우, 400 에러코드 (StatusCodes.BAD_REQUEST)
로 응답을 내려주고 있습니다.
인증 토큰이 없는 경우이므로 401 에러코드 (https://developer.mozilla.org/ko/docs/Web/HTTP/Status/401) 로 내려주는 것이 맞지 않을까 싶은데.
어떤가용??

https://github.com/starkoora/wanted-pre-onboarding-challenge-fe-1-api/blob/master/middleware/validateToken.ts

**Comment by starkoora** [comment]
@dhsimpson 좋은 제안 감사합니다 제가 고쳐도 되지만 컨트리뷰트를 위해 PR 올려주시면 바로 머지할게요

**Comment by dhsimpson** [comment]
@starkoora  받아주셔서 감사합니다~! pr 날렸습니다 ㅎㅎ

**Comment by starkoora** [comment]
https://github.com/starkoora/wanted-pre-onboarding-challenge-fe-1-api/pull/23 에서 resolve
