### ISSUE TITLE
[질문]타입 에러에 대해서 질문드립니다. 

### ISSUE THREAD

**Issue by HelloHailie** [starkoora/wanted-pre-onboarding-challenge-fe-1#31]
많은 분들의 코드를 보니 mutation을 hook으로 사용하는게 깔끔한 것 같아서 도전하고 있는데요.
useMutation으로 받아온 데이터를 onSuccess와, onError인 상태로 나누고 있는데 이때 데이터(loginData) 타입을 
`export interface AuthResponse {
  message: string;
  token: string;
}
`
이렇게 설정해서 넣어주고 있는데 에러가 나고 있습니다. 

onSuccess시 데이터를 콘솔에 찍어보면 아래와 같이 나와서 AuthResponse를 위와 같이 설정했습니다. 
`{message: '성공적으로 로그인 했습니다', token: 'eyJhbGciOiJIUzI1NiJ9.dGVzdEB0ZXN0LmNvbQ.ryq30DukSEV3o-wUkSBPVgBNQ8eBN0FO5Hog7vjsUiI'}`

타입 스크립트를 배우고 있는 입장이라서 이 문제를 해결할 수 있는 키워드라도 알려주시면 감사하겠습니다. 

**전체 코드**
<img width="932" alt="스크린샷 2023-01-17 오전 11 33 01" src="https://user-images.githubusercontent.com/103437860/212797129-655f3230-b8a8-4936-b75a-80d64542e29c.png">

`
import { useMutation } from "@tanstack/react-query";
import AuthAPI from "../../../api/auth";
import { AuthResponse, UserInfo, TNavigate } from "../../../types/model";

const useLogin = (navigate: TNavigate) => {
  return useMutation((userInfo: UserInfo) => AuthAPI.login(userInfo), {
    onSuccess: (loginData: AuthResponse) => {
      console.log(loginData);
      const token = loginData.token;
      localStorage.setItem("token", token);
      navigate("/todo");
    },
    onError: (loginData: any) => {
      alert(loginData.response.data.details);
    },
  });
};

export default useLogin;
`

**에러 메세지**
`TS2769: No overload matches this call.
  Overload 1 of 4, '(mutationFn: MutationFunction<AuthResponse, UserInfo>, options?: Omit<UseMutationOptions<AuthResponse, any, UserInfo, unknown>, "mutationFn"> | undefined): UseMutationResult<...>', gave the following error.`

**Comment by Yoon-Hae-Min** [comment]
공식문서를 보면 useMutatioin의 첫번째 인자가 `(variables: TVariables) => Promise<TData>`로 되어있고 axios.post는 `(url: string, data?: D, config?: AxiosRequestConfig<D>): Promise<R>;` 로 되어있습니다. 즉 useMutation의 첫번째 인자로 axios.post를 넘겨줘야 하는데 작성자님이 작성하신 코드에서는 axios.post를 반환하는 함수`(userInfo: UserInfo) => AuthAPI.login(userInfo)`로 사용해서 문제가 생긴게 아닐까 조심스럽게 생각해 봅니다 :)

https://tanstack.com/query/v4/docs/react/reference/useMutation
https://github.com/axios/axios/blob/v1.x/index.d.cts#L118

**Comment by HelloHailie** [comment]
> 공식문서를 보면 useMutatioin의 첫번째 인자가 `(variables: TVariables) => Promise<TData>`로 되어있고 axios.post는 `(url: string, data?: D, config?: AxiosRequestConfig<D>): Promise<R>;` 로 되어있습니다. 즉 useMutation의 첫번째 인자로 axios.post를 넘겨줘야 하는데 작성자님이 작성하신 코드에서는 axios.post를 반환하는 함수`(userInfo: UserInfo) => AuthAPI.login(userInfo)`로 사용해서 문제가 생긴게 아닐까 조심스럽게 생각해 봅니다 :)
> 
> https://tanstack.com/query/v4/docs/react/reference/useMutation https://github.com/axios/axios/blob/v1.x/index.d.cts#L118

답변 감사합니다!
`AuthAPI.login(userInfo)` 이 부분이 axios를 사용하는 부분이라서 인자를 잘못 받아와서 생긴 문제는 아니라고 생각했습니다.

참고로 `onSuccess: (loginData: AuthResponse)`를  `onSuccess: (loginData: any)`로 수정하면 문제는 발생하지 않습니다😂

**Comment by foreknowledge** [comment]
```ts
useMutation((userInfo: UserInfo) => AuthAPI.login(userInfo), {
  onSuccess: (loginData: AuthResponse) => {
  },
  onError: (loginData: any) => {
    ...
  },
}
```
위 코드에서 useMutation은 내부 인자들을 보고 타입을 추론하게 되는데요. 첫 번째 인자인 mutationFn의 타입을 보면 `AuthAPI.login(userInfo)`의 타입이 `(data: UserInfo) => any`로 추정되는 걸 볼 수 있어요. 그러면 onSuccess로 넘어가는 데이터의 타입은 any 타입이 넘어가는 걸 기대할텐데 AuthResponse 타입이라고 하니까 타입 에러를 내는것이죠.

즉, AuthAPI.login의 타입을 `(data: UserInfo) => AuthResponse` 타입으로 만들면 에러가 사라질거에요!

```ts
const AuthAPI = {
  signUp: (data: UserInfo) => {
    return axiosInstance.post("/users/create", data);
  },
  login: (data: UserInfo) => {
    return axiosInstance.post("/users/login", data);
  },
};
```
위 코드에서 `axiosInstance.post`의 리턴 결과가 `Promise<any>`로 추정되기 때문에 명시적으로 `Promise<AuthResponse>` 타입을 리턴하도록 처리하면 될 것 같습니다!

**Comment by HelloHailie** [comment]
> ```ts
> useMutation((userInfo: UserInfo) => AuthAPI.login(userInfo), {
>   onSuccess: (loginData: AuthResponse) => {
>   },
>   onError: (loginData: any) => {
>     ...
>   },
> }
> ```
> 
> 위 코드에서 useMutation은 내부 인자들을 보고 타입을 추론하게 되는데요. 첫 번째 인자인 mutationFn의 타입을 보면 `AuthAPI.login(userInfo)`의 타입이 `(data: UserInfo) => any`로 추정되는 걸 볼 수 있어요. 그러면 onSuccess로 넘어가는 데이터의 타입은 any 타입이 넘어가는 걸 기대할텐데 AuthResponse 타입이라고 하니까 타입 에러를 내는것이죠.
> 
> 즉, AuthAPI.login의 타입을 `(data: UserInfo) => AuthResponse` 타입으로 만들면 에러가 사라질거에요!
> 
> ```ts
> const AuthAPI = {
>   signUp: (data: UserInfo) => {
>     return axiosInstance.post("/users/create", data);
>   },
>   login: (data: UserInfo) => {
>     return axiosInstance.post("/users/login", data);
>   },
> };
> ```
> 
> 위 코드에서 `axiosInstance.post`의 리턴 결과가 `Promise<any>`로 추정되기 때문에 명시적으로 `Promise<AuthResponse>` 타입을 리턴하도록 처리하면 될 것 같습니다!

내부 인자의 타입을 확인해서 리턴하는 타입을 명시적으로 설정해주어야하는군요!
타입스크립트 공부를 본격적으로 해야겠네요ㅎㅎ 도움 주셔서 감사합니다!
