### ISSUE TITLE
map 사용하여 하위 컴포넌트에 props 전달 오류를 만났습니다...

### ISSUE THREAD

**Issue by nicehyun** [starkoora/wanted-pre-onboarding-challenge-fe-1#32]
안녕하세요 타입스크립트와 리액트 조합이 아직 적응이 안되는 타린이입니다 ㅠㅠ

<img width="724" alt="스크린샷 2023-01-17 오후 2 21 40" src="https://user-images.githubusercontent.com/85052351/212816450-b91c48bc-1c1e-449b-a3fa-1ab813cc8a75.png">

toDoList는 투두데이터가 담긴 데이터인데 해당 데이터를 map 돌려서 ToDoItem 컴포넌트에 props로 전달하려하는데 

<img width="638" alt="스크린샷 2023-01-17 오후 2 24 01" src="https://user-images.githubusercontent.com/85052351/212816722-eedd8b94-8a75-408a-8f4c-e5fed22b6178.png">

요런 타입 에러를 만났습니다...😭

<img width="503" alt="스크린샷 2023-01-17 오후 2 24 33" src="https://user-images.githubusercontent.com/85052351/212816791-2b506a76-f7d8-469b-a378-1e7213877f35.png">

ToDoItem 컴포넌트에서는 props를 이렇게 받고 있는데 왜 onClickDelete가 없다고 타입에러가 발생하는 걸까요...

<img width="598" alt="image" src="https://user-images.githubusercontent.com/85052351/212817220-0e3a9ae7-adb1-4f15-8f8e-317d8d232883.png">

onClickDelete이 IToDoItemProps에 필수라고하는데 ..

<img width="511" alt="image" src="https://user-images.githubusercontent.com/85052351/212817346-d9ddbc5c-4838-4313-8bd7-1799a702e505.png">

onClickDelete은 하위 컴포넌트에서 만들어서 View로 전달하는데 왜 에러가 발생하는지 감이 잡히지 않네요 😨

<img width="382" alt="스크린샷 2023-01-17 오후 2 30 35" src="https://user-images.githubusercontent.com/85052351/212817494-a5b9dcb3-237b-499a-ad64-332b3e45e958.png">

인터페이스에 onClickDelete를 옵셔널로 변경하니 오류는 사라지는데 왜 이런건지 알려주실 수 있을까여..

**Comment by young-st511** [comment]
안녕하세요! 단순하게 `ITodoItemProps`에는 onClickDelete가 정의 되어 있지만 TodoItem에는 들어가지 않아서 일어나는것 같습니다. map 돌리실 때 onClickDelete도 넣어주시면 해결 될거예요😊

**Comment by foreknowledge** [comment]
의도하신 코드가 https://codesandbox.io/s/eloquent-maria-vowp4i?file=/src/App.tsx 이런 형태인 것처럼 보이는데 맞나요??
샌드박스로 테스트 했을 때는 문제가 없는데 뭔가 import의 문제가 있는 게 아닐까요??

**Comment by nicehyun** [comment]
> 의도하신 코드가 https://codesandbox.io/s/eloquent-maria-vowp4i?file=/src/App.tsx 이런 형태인 것처럼 보이는데 맞나요?? 샌드박스로 테스트 했을 때는 문제가 없는데 뭔가 import의 문제가 있는 게 아닐까요??

와!!!! 진짜 감사합니다 ㅠㅠ import를 view 파일에서 하고있었습니다.... 감사합니다😭 너무 멍청한 실수였네여..
