### ISSUE TITLE
[질문] axios Client 를 여러개 만들어도 좋을까요?

### ISSUE THREAD

**Issue by dhsimpson** [starkoora/wanted-pre-onboarding-challenge-fe-1#34]
todo 의 CRUD 에 모두 auth token이 필요해

axios interceptor 헤더에 auth token 을 기본적으로 넣어 주는 axios Client 를 만들었습니다.

[axios client](https://github.com/dhsimpson/wanted-pre-onboarding-challenge-fe-1/blob/main/src/utils/axiosClient.ts)
[axios client를 사용한 todo API](https://github.com/dhsimpson/wanted-pre-onboarding-challenge-fe-1/blob/main/src/api/todoApi.ts)

반면에 로그인/회원가입 을 위한 api 에선 auth token 을 사용하지 않아 axiosClient 를 사용하지 않고 있어요.
(가능한 auth token 은 network 에 노출하지 않는 것이 좋다고 판단해서요)
[axios client를 사용하지 않은 auth API](https://github.com/dhsimpson/wanted-pre-onboarding-challenge-fe-1/blob/main/src/api/authApi.ts)

굳이 두 경우를 나눠 api 호출 하고 있는 것인가 생각이 들어 질문 드립니다.
(그렇지 않다면
1. base url 을 가진 axios client 를 만들고, 
2. 해당 axios client 를 extend 해 auth token 을 추가한 axios client 까지 두 개의 axios client 를 만들까도 생각 중이에요
)

**Comment by starkoora** [comment]
@dhsimpson 그렇게 하셔도 문제는 없을거 같습니다. 그런데 요청을 보낼 때 함수 하나 만들어서 api 경로 별로 인터셉터에서 토큰 필요 여부를 분기 해줘도 괜찮지 않을까 싶네요.

**Comment by dhsimpson** [comment]
@starkoora  감사합니다! 참고해 볼게요!
